# Generated by Django 6.0.6 on 2026-06-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('product_id', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('final_price', models.FloatField()),
                ('payment_method', models.CharField(db_index=True, max_length=255)),
                ('purchase_date', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
