# Generated by Django 6.0.6 on 2026-09-10 13:50

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_agentmessage_alert_goalplan_pricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmessage',
            name='agent_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agentmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agentmessage',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goalplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goalplan',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='product_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default=dashboard.models.generate_product_id, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_id',
            field=models.CharField(blank=True, default=dashboard.models.generate_product_id, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
